services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    ports:
      - 2222:22
  
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  valkey:
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data
  
volumes:
  pgdata:
  valkey_data:
